Repository MLSA-Mehran-UET/learn2code, pull requests merged in 2021-10, with the labels that each got.

#3 Create mergeSort.py
  Data Structures/Sorting/Python/mergeSort.py
Labels: hacktoberfest

#2 Create readme.md
  Data Structures/readme.md
Labels: hacktoberfest

#14 Created Recursive Insertion Sort in Python
  Python/Sorting/recursiveInsertionSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#13 Inserted Insertion Sort Algorithm in Python
  Python/insertionSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#12 Inserted Recursive Bubble Sort Algorithm in Python
  Python/recursiveBubbleSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#11 Create bubbleSort.py
  Python/Sorting/bubbleSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#9 Create binarySearch.cpp
  Data Structures/Searching/C++/binarySearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#8 Added C++ code of Bubble Sort
  Data Structures/Sorting/C++/Bubble Sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#7 sorting using dynamic allocation
  Data Structures/Sorting/C++/sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#20 Create heapSort.py
  Python/Sorting/heapSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#19 Create countSort.py
  Python/Sorting/countSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#18 Create iterativeQuickSort.py
  Python/Sorting/iterativeQuickSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#17 Create quickSort.py
  Python/Sorting/quickSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#16 Create iterativeMergeSort.py
  Python/Sorting/iterativeMergeSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#15 Create mergeSort.py
  Python/Sorting/mergeSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#29 Create cockTailSort.py
  Python/Sorting/cockTailSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#28 Create cycleSort.py
  Python/Sorting/cycleSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#27 Create pigeonHoleSort.py
  Python/Sorting/pigeonHoleSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#26 Create combSort.py
  Python/Sorting/combSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#25 Create timSort.py
  Python/Sorting/timSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#24 Create shellSort.py
  Python/Sorting/shellSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#23 Create bucketSort.py
  Python/Sorting/bucketSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#22 Create radixSort.py
  Python/Sorting/radixSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#21 Added selection sort for Python
  Python/Sorting/selection_sort.py
Labels: hacktoberfest-accepted, hacktoberfest

#34 Create gnomeSort.py
  Python/Sorting/gnomeSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#33 Create bogoSort.py
  Python/Sorting/bogoSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#32 Create binaryInsertion.py
  Python/Sorting/binaryInsertion.py
Labels: hacktoberfest-accepted, hacktoberfest

#31 Create pancakeSort.py
  Python/Sorting/pancakeSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#30 Create bitonicSort.py
  Python/Sorting/bitonicSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#39 Create binarySearch.py
  Python/Searching/binarySearch.py
Labels: hacktoberfest-accepted, hacktoberfest

#38 Create exponentialSearch.py
  Python/Searching/exponentialSearch.py
Labels: hacktoberfest-accepted, hacktoberfest

#37 Create interpolationSearch.py
  Python/Searching/interpolationSearch.py
Labels: hacktoberfest-accepted, hacktoberfest

#36 Create jumpSearch.py
  Python/Searching/jumpSearch.py
Labels: hacktoberfest-accepted, hacktoberfest

#35 Create complex-numbers-addition.cpp
  C++/complex-numbers-addition.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#44 Create recursiveInsertionSort.cpp
  C++/recursiveInsertionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#43 Create insertionSort.cpp
  C++/insertionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#42 Create recursiveBubbleSort.cpp
  C++/recursiveBubbleSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#41 Create bubbleSort.cpp
  C++/bubbleSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#40 Create selectionSort.cpp
  C++/selectionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#45 Add bipartite graph solution
  C++/bipartite.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#47 Create Health Monitorization
  C++/Health Monitorization
Labels: hacktoberfest-accepted, hacktoberfest

#53 Create bubblesort.java
  Java/bubblesort.java
Labels: hacktoberfest-accepted, hacktoberfest

#52 Create insertiosort.java
  Java/insertiosort.java
Labels: hacktoberfest-accepted, hacktoberfest

#50 Create mergeSort.java
  Java/mergeSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#49 Create dfs.cpp
  C++/dfs.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#48 Create selectionSort.java
  Java/selectionSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#55 Created mysql_python_connector file
  mysql_python_connector.py
Labels: hacktoberfest-accepted, hacktoberfest

#51 Create directed_cycle.cpp
  C++/directed_cycle.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#57 Create bellmanford.cpp
  C++/bellmanford.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#56 Create udemy_scrape.py
  Python/udemy_scrape.py
Labels: hacktoberfest-accepted, hacktoberfest

#66 Create Data Science Stream
  Data Science/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#67 Create Merge_Sort.cpp
  Data Structures/Sorting/C++/Merge_Sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#71 Starting Program in Dart
  Dart/helloworld.dart
Labels: hacktoberfest-accepted

#75 Create DFS.py
  Python/Searching/DFS.py
Labels: hacktoberfest-accepted, hacktoberfest

#74 Create BFS.java
  Java/Search/BFS.java
Labels: hacktoberfest-accepted, hacktoberfest

#73 Create BFS.cs
  C#/Searching/BFS.cs
Labels: hacktoberfest-accepted, hacktoberfest

#72 Create BFS.py
  Python/Searching/BFS.py
Labels: hacktoberfest-accepted, hacktoberfest

#142 Create Example for Exceptional Handling
  Python/Exception_handling.py
Labels: hacktoberfest-accepted, hacktoberfest

#139 Create Example of Threading
  Python/Threading_Example.py
Labels: hacktoberfest-accepted, hacktoberfest

#138 Create Example of regression
  Python/Regression_Example.py
Labels: hacktoberfest-accepted, hacktoberfest

#137 Rolling a Dice
  Python/Rolling_Dice.py
Labels: hacktoberfest-accepted, hacktoberfest

#165 Growable List
  Dart/GrowableList.dart
Labels: hacktoberfest-accepted, hacktoberfest

#164 Fixed Length List
  Dart/FixedLengthList.dart
Labels: hacktoberfest-accepted, hacktoberfest

#163 Closures
  Dart/ClosuresInDart.dart
Labels: hacktoberfest-accepted, hacktoberfest

#162 CallableClass
  Dart/CallableClass.dart
Labels: hacktoberfest-accepted, hacktoberfest

#167 Set
  Dart/Set.dart
Labels: hacktoberfest-accepted, hacktoberfest

#166 Map
  Dart/Map.dart
Labels: hacktoberfest-accepted, hacktoberfest

#160 GGPLOTS
  R-Programming/GGPLOTS
Labels: hacktoberfest-accepted, hacktoberfest

#159 Add new Js code
  Dart/Dart program to check if a number is prime or not.dart
  Javascript/Animations.js
  Javascript/Animationsindex.html
  Javascript/JSCharts.html
  Javascript/JsCalculator.html
  Javascript/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#158 Create dice sum program
  C++/dice sum program
Labels: hacktoberfest-accepted, hacktoberfest

#140 Create Example of regrassion
  Python/Example of regrassion.py
Labels: hacktoberfest-accepted, hacktoberfest

#141 Create Example to connect MySQL data base
  Python/Example to connect MySQL data base.py
Labels: hacktoberfest-accepted, hacktoberfest

#157 Create heart-shape-pattern
  C++/heart-shape-pattern
Labels: hacktoberfest-accepted, hacktoberfest

#156 Create triangle pattern
  C++/triangle pattern
Labels: hacktoberfest-accepted, hacktoberfest

#155 Create Simple-pattern
  C++/Simple-pattern
Labels: hacktoberfest-accepted, hacktoberfest

#154 Create hollow-triangle star
  Javascript/hollow-triangle star
Labels: hacktoberfest-accepted, hacktoberfest

#152 Create Left triangle pattern
  Javascript/Left triangle pattern
Labels: hacktoberfest-accepted, hacktoberfest

#151 Create Right Triangle Pattern
  Javascript/Right Triangle Pattern
Labels: hacktoberfest-accepted, hacktoberfest

#150 Create square star pattern
  Javascript/square star pattern
Labels: hacktoberfest-accepted, hacktoberfest

#149 Create User_defined_Exception.cs
  C#/User_defined_Exception.cs
Labels: hacktoberfest-accepted, hacktoberfest

#168 Added Python Programs
  Python/firstandlastelementinsortedarray.py
  Python/foursum.py
  Python/generateparanthesis.py
  Python/lowestcommonancestor.py
  Python/mergeKLL.py
  Python/mergeLL.py
  Python/partitiondisjoint.py
  Python/searchhinsortedarray.py
  Python/sudoku_solver.py
  Python/sumequalszero.py
  Python/threesumclosest.py
Labels: hacktoberfest-accepted, hacktoberfest
